/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package trainingsimgui;

import Controller.CavityController;

/**
 *
 * @author olli
 */
public class CapacityRowPanel extends javax.swing.JPanel {

    /**
     * Creates new form CapacityRowPanel
     */
    public CapacityRowPanel() {
        initComponents();
    }
    
    public void init(int id, CavityController controller) {
        this.id=id;
        this.controller=controller;
        this.offset=0;
    }
    
    private float getCuc(){
        if (controller==null) return 0;
        float f=controller.getCurCav().getCucAt(id+offset)/controller.getCurCav().getTopCap();
    return f;
    }
    
    private float getMic(){
        if (controller==null) return 0;
        float f=controller.getCurCav().getMicAt(id+offset)/controller.getCurCav().getTopCap();
    return f;
    }
    
    private float getMac(){
        if (controller==null) return 0;
        float f=controller.getCurCav().getMacAt(id+offset)/controller.getCurCav().getTopCap();
    return f;
    }
    
   public void setOffset(int offset){
        this.offset=offset;
        float top=controller.getCurCav().getTopCap();
       
        minCapBar.setValue((int)(getMic()*1000f));   
        micVal.setText(String.format("%2.2f cm",controller.getCurCav().getMicAt(id+offset)));
        curCapBar.setValue((int)(getCuc()*1000f));
        cucVal.setText(String.format("%2.2f cm",controller.getCurCav().getCucAt(id+offset)));
        maxCapBar.setValue((int)(getMac()*1000f));
        macVal.setText(String.format("%2.2f cm",controller.getCurCav().getMacAt(id+offset)));
        depth.setText(String.format("%1d cm",id+offset));
   }

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        depth = new javax.swing.JLabel();
        minCapBar = new javax.swing.JProgressBar();
        curCapBar = new javax.swing.JProgressBar();
        maxCapBar = new javax.swing.JProgressBar();
        micVal = new javax.swing.JLabel();
        cucVal = new javax.swing.JLabel();
        macVal = new javax.swing.JLabel();

        depth.setText(""+(id+offset));

        minCapBar.setMaximum(1000);
        minCapBar.setValue((int)(getMic()*1000f));
        minCapBar.setMaximumSize(new java.awt.Dimension(80, 14));

        curCapBar.setMaximum(1000);
        curCapBar.setValue((int)(getCuc()*1000f));
        curCapBar.setMaximumSize(new java.awt.Dimension(80, 14));

        maxCapBar.setMaximum(1000);
        maxCapBar.setValue((int)(getMac()*1000f));
        maxCapBar.setMaximumSize(new java.awt.Dimension(80, 14));

        micVal.setText("jLabel1");

        cucVal.setText("jLabel2");

        macVal.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(depth, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(micVal)
                    .addComponent(minCapBar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(curCapBar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cucVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(macVal)
                    .addComponent(maxCapBar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depth)
                    .addComponent(micVal)
                    .addComponent(cucVal)
                    .addComponent(macVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minCapBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curCapBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxCapBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    public int id,offset;
    CavityController controller;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cucVal;
    private javax.swing.JProgressBar curCapBar;
    private javax.swing.JLabel depth;
    private javax.swing.JLabel macVal;
    private javax.swing.JProgressBar maxCapBar;
    private javax.swing.JLabel micVal;
    private javax.swing.JProgressBar minCapBar;
    // End of variables declaration//GEN-END:variables
    
}
